# Generated by Django 2.2.1 on 2019-05-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blogText',
            field=models.TextField(),
        ),
    ]
